### ISSUE TITLE
SQL Injection Prevention

### ISSUE THREAD

**Issue by nicolastakashi** [nicolastakashi/flepper#17]
It is necessary to implement prevention against SQL Injection, because today this is a security failure in the writing of queries.

**Comment by reinaldocoelho** [comment]
To create this, don't would be better to use parameters like supported by dapper to do that?
And the prevention will be native.

Example: "select * from  table where id = @id"

**Comment by AlbertoMonteiro** [comment]
@reinaldocoelho the issue is done in PR #27. You can check and talk about the implementation!

**Comment by reinaldocoelho** [comment]
Thank you @AlbertoMonteiro.
